### ISSUE TITLE
.send error

### ISSUE THREAD

**Issue by wil2005-development** [RoqueDEV/FivemServerStatus#12]
TypeError: Cannot read property 'send' of undefined
    at Client.<anonymous> (C:\Users\fivem\Desktop\Discord Bot\bot.js:349:49)
    at Client.emit (events.js:333:22)
    at MessageCreateHandler.handle (C:\Users\fivem\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\fivem\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\fivem\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\fivem\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\fivem\Desktop\Discord Bot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:321:20)
    at Receiver.receiverOnMessage (C:\Users\fivem\Desktop\Discord Bot\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:321:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! FiveM-Server-Status-bot@1.0.0 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the FiveM-Server-Status-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fivem\AppData\Roaming\npm-cache\_logs\2020-02-20T13_32_59_001Z-debug.log

Whats is the problem?

**Comment by RoqueDEV** [comment]
Make sure to read the wiki : https://github.com/RoqueDEV/fivemserverstatus/wiki
