### ISSUE TITLE
discord.js is missing

### ISSUE THREAD

**Issue by KnifyDodo** [RoqueDEV/fivemserverstatus#21]
Hey, the discord.js file is missing..

```
Error: Cannot find module 'discord.js'
Require stack:
- C:\Users\Development\Desktop\Scripts\Discord Bot\bot.js
- C:\Users\Development\Desktop\Scripts\Discord Bot\index.js
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980
:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:1042:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:77:18)?[39m
    at Object.<anonymous> (C:\Users\Development\Desktop\Scripts\Discord Bot\bot.
js:3:17)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1156:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:1
0)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:1042:19)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [
    ?[32m'C:\\Users\\Development\\Desktop\\Scripts\\Discord Bot\\bot.js'?[39m,
    ?[32m'C:\\Users\\Development\\Desktop\\Scripts\\Discord Bot\\index.js'?[39m
  ]
}
```

**Comment by LeManock** [comment]
npm install discord.js
