### ISSUE TITLE
if you are getting error

### ISSUE THREAD

**Issue by unknowndeira** [RoqueDEV/fivemserverstatus#9]
contact with me i can help you guys.

**Comment by saulienis** [comment]
Hey,i was trying to reach out to you, couldnt find out how for the life of me. Are you some type of support for this resource?

**Comment by unknowndeira** [comment]
Yes, I can help you

**Comment by saulienis** [comment]
![71706025-5cb97580-2dda-11ea-9dc5-9387ab3a6c9e (1)](https://user-images.githubusercontent.com/52180748/71783222-8e4d5f00-2fdb-11ea-9c9e-0248aad100c4.png)

Right.so any idead on this? Server is on,looks like the bot starts,but it seems it cannot see it.maybe because i am not listing my server on the server list is the issue?

**Comment by JesperS4** [comment]
Hey I have a problem im starting up the console it's my server is connect ect. But then it's says update failed, can you help me please?

**Comment by saulienis** [comment]
> Hey I have a problem im starting up the console it's my server is connect ect. But then it's says update failed, can you help me please?

Make sure you have json installed if launching from windows.and delete the message id

**Comment by unknowndeira** [comment]
You can add me from Discord and i can help ya. DΣIЯΛ#0010

**Comment by saulienis** [comment]
Seems to made it work. But now it doesnt see if the server is on or off, but thats better then nothing

**Comment by saulienis** [comment]
theDeira,i cannot add you. you do not accept requests
Add me
Saul.#3949

**Comment by Nilsfctwente** [comment]
i cant see the server

**Comment by KotSerious** [comment]
hello, im getting url not defined when i set it up. url in config.json correct
![image](https://user-images.githubusercontent.com/59852842/75169780-f4886f80-574a-11ea-9b6e-f10bae1afa91.png)

**Comment by Nilsfctwente** [comment]
hey i have an error

does anyone know the fix
<img width="578" alt="Screenshot_1" src="https://user-images.githubusercontent.com/57631652/77928605-e9c07d80-72a8-11ea-8aa0-ac9fd5b2362d.png">

**Comment by RoqueDEV** [comment]
@Nilsfctwente start it by using npm start.

**Comment by alianceee** [comment]
Hello, i am getting an error that my "update channel is not set", but it is.

**Comment by MeshX4** [comment]
@

> You can add me from Discord and i can help ya. DΣIЯΛ#10

@theDeira can you add me I am trying to make it work but no luck tried a lot of thinks still I cant seem to set the message where it shows the server status. 

this is my discord if you kindly can reach me @Mesh 👑#1111

thank you

**Comment by RoqueDEV** [comment]
@MeshX4 what is your discord name? I am trying to add you but your discord name is incorrect.

**Comment by AlexFernando001** [comment]
C:\Users\gulbe\Desktop\DiscordBot>echo "Starting"
"Starting"

C:\Users\gulbe\Desktop\DiscordBot>node ./index.js
internal/modules/cjs/loader.js:969
throw err;
^

Error: Cannot find module 'discord.js'
Require stack:

C:\Users\gulbe\Desktop\DiscordBot\bot.js
C:\Users\gulbe\Desktop\DiscordBot\index.js
�[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)�[39m
�[90m at Function.Module._load (internal/modules/cjs/loader.js:842:27)�[39m
�[90m at Module.require (internal/modules/cjs/loader.js:1026:19)�[39m
�[90m at require (internal/modules/cjs/helpers.js:72:18)�[39m
at Object. (C:\Users\gulbe\Desktop\DiscordBot\bot.js:3:17)
�[90m at Module._compile (internal/modules/cjs/loader.js:1138:30)�[39m
�[90m at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)�[39m
�[90m at Module.load (internal/modules/cjs/loader.js:986:32)�[39m
�[90m at Function.Module._load (internal/modules/cjs/loader.js:879:14)�[39m
�[90m at Module.require (internal/modules/cjs/loader.js:1026:19)�[39m {
code: �[32m'MODULE_NOT_FOUND'�[39m,
requireStack: [
�[32m'C:\Users\gulbe\Desktop\DiscordBot\bot.js'�[39m,
�[32m'C:\Users\gulbe\Desktop\DiscordBot\index.js'�[39m
]
}
C:\Users\gulbe\Desktop\DiscordBot>PAUSE
Press any key to continue . . .




Discord: Alex1#0001

**Comment by NyxBoi** [comment]
> ![71706025-5cb97580-2dda-11ea-9dc5-9387ab3a6c9e (1)](https://user-images.githubusercontent.com/52180748/71783222-8e4d5f00-2fdb-11ea-9c9e-0248aad100c4.png)
> 
> Right.so any idead on this? Server is on,looks like the bot starts,but it seems it cannot see it.maybe because i am not listing my server on the server list is the issue?

getting the same error, how did you solve it ?

**Comment by benlee057** [comment]
im getting this 

DiscordAPIError: Invalid Form Body
embed.author.icon_url: Not a well formed URL.
    at C:\Users\Administrator\Desktop\DiscordBot\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\Administrator\Desktop\DiscordBot\node_modules\snekfetch\src\index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  path: '/api/v7/channels/753416954399817798/messages',
  code: 50035,
  method: 'POST'
}

**Comment by TheHans58** [comment]
> > ![71706025-5cb97580-2dda-11ea-9dc5-9387ab3a6c9e (1)](https://user-images.githubusercontent.com/52180748/71783222-8e4d5f00-2fdb-11ea-9c9e-0248aad100c4.png)
> > Doğru. Bu konuda herhangi bir fikir var mı? Sunucu açık, bot başlıyor gibi görünüyor, ancak göremiyor. Belki de sunucumu sunucu listesinde listelemediğim için sorun olabilir mi?
> 
> aynı hatayı alıyorsun, nasıl çözdün?

Hello, I have the same problem, can anyone solve it?

**Comment by unknowndeira** [comment]
You have to start bot where you are starting the server and you should check **sv_endpointprivacy** command in server.cfg

**Comment by TheHans58** [comment]
hello now the bot stops refreshing by itself suddenly. sometimes stops after 3 days, sometimes after 10 minutes
![dsdadasd](https://user-images.githubusercontent.com/68406822/94323391-4d98da00-ff9e-11ea-8f3d-5a5117d05c71.png)

**Comment by Tamir112** [comment]
I have a problem when I start the script I get this
![Screenshot 2020-09-29 232626](https://user-images.githubusercontent.com/72105487/94612053-3c581200-02ab-11eb-9af6-5845f8576af0.jpg)

**Comment by Tamir112** [comment]
And this one
![Uploading and this shit.jpg…]()

**Comment by Tamir112** [comment]
And this as well any fix?
![and this shit](https://user-images.githubusercontent.com/72105487/94612444-c902d000-02ab-11eb-8aca-0c9401dae76d.jpg)
Discord: Tamir112#6969

**Comment by Locopengu96** [comment]
Yeah, i have a question. 

Where do i put my Information in? Like Bot Token - Channel ID etc?

**Comment by AlexFernando001** [comment]
> Yeah, i have a question.
> 
> Where do i put my Information in? Like Bot Token - Channel ID etc?

You can edit them at config.lua :)

**Comment by Robbedoes24** [comment]
I'm very new to all this, and i don't know how to start the bot. I've done all the prep, but i can't figure out how to succesfully start the bot. Anyone here who wants to help me?

**Comment by Eazzyy** [comment]
Hi, the bot keeps saying the server is offline, when the server isn't.. it fixed itself before but now isn't.... Does anyone know how to fix this issue?

**Comment by Jenskuin04** [comment]
i dont understand how to start the bot i think i did everything correctly but the bot only gives errors and nothing in discord does someone know the solution
![image](https://user-images.githubusercontent.com/82210695/114162497-70328500-9929-11eb-90f7-223ed890b21d.png)
i tried all the ways to start it but it doesnt work

**Comment by Chrissuboi** [comment]
> contact with me i can help you guys.

can you give your discord?It would be great,i can send there screens.

**Comment by Abusse7620** [comment]
can some one help me install it?

**Comment by Abusse7620** [comment]
my discord its Abusse#7620
